apiVersion: v1
kind: ServiceAccount
metadata:
  name: magicbox-staging
---
apiVersion: v1
kind: Service
metadata:
  name: magicbox-staging
  labels:
    app: magicbox-staging
    service: magicbox-staging
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 5301
  selector:
    app: magicbox-staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magicbox-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magicbox-staging
      version: v1
  template:
    metadata:
      labels:
        app: magicbox-staging
        version: v1
    spec:
      serviceAccountName: magicbox-staging
      containers:
      - image: nielsgregers/magicbox-web:latest
        imagePullPolicy: IfNotPresent
        name: magicbox-staging
        ports:
        - containerPort: 5301


