apiVersion: v1
kind: Namespace
metadata:
  annotations:
    fluxcd.io/ignore: "false"
    linkerd.io/inject: enabled
  name: percona
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: percona
  namespace: percona
spec:
  interval: 5m0s
  url: https://percona.github.io/percona-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: percona-mongodb
  namespace: percona
spec:
  interval: 5m
  chart:
    spec:
      chart: psmdb-operator
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: percona
      interval: 1m
  values:
    replicaCount: 1