apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pmm
  namespace: percona
spec:
  interval: 5m
  chart:
    spec:
      chart: pmm
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: percona
      interval: 1m
  values:
    replicaCount: 1