apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
spec:
  selector:
    matchLabels:
      app: workers
  replicas: 3
  template:
    metadata:
      labels:
        app: workers
    spec: 
      containers:
      - name: worker
        image: nielsgregers/magicbox-workers:v6
        env:
        - name: DEBUG
          value: magicbox*
        - name: REDIS
          value: redis://redis-prod.redis:6379
        - name: EXCHAPPID
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHAPPID
        - name: EXCHORGANIZATION  
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHORGANIZATION   
        - name: EXCHCERTIFICATE
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHCERTIFICATE  
        - name: EXCHCERTIFICATEPASSWORD
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHCERTIFICATEPASSWORD                
