
apiVersion: batch/v1
kind: CronJob
metadata:
  name: syncdomains
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      backoffLimit: 3

      template:
        metadata:
          labels:
            app: pwsh2
        spec: 
          restartPolicy: Never
          volumes:
          - name: shared-data
            emptyDir: {}          
          containers:
        
          - name: koksmat-cli
            image: ghcr.io/koksmat-com/koksmat:v1.0.5
            command: ["koksmat"]
            args: ["sync","domains"]
            # args: ["serve"]               
            volumeMounts:
            - name: shared-data
              mountPath: /exchange            
            env:
            - name: EXCHAPPID
              valueFrom:
                secretKeyRef:
                  name: exchange
                  key: EXCHAPPID
            - name: EXCHORGANIZATION  
              valueFrom:
                secretKeyRef:
                  name: exchange
                  key: EXCHORGANIZATION   
            - name: EXCHCERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: exchange
                  key: EXCHCERTIFICATE  
            - name: EXCHCERTIFICATEPASSWORD
              valueFrom:
                secretKeyRef:
                  name: exchange
                  key: EXCHCERTIFICATEPASSWORD  
            - name: DEBUG
              value: magicbox*
            - name: DATAOUT
              value: /exchange
            - name: DATABASE
              value: christianiabpos
            - name: DATABASEADMIN
              valueFrom:
                secretKeyRef:
                  name: exchange
                  key: DATABASEADMIN
            - name: DATABASEPASSWORD
              valueFrom:
                secretKeyRef:
                  name: exchange
                  key: DATABASEPASSWORD
            - name: DATABASEURL
              value:  mongodb://prod-mongos.percona:27017
