#
# This routes any traffic send to any domains to APISIX gateway for routing
# Benefit here, is that is no TLS stuff running, it simply accepts all traffic
# We use the plugins in APISIX to restrict what get accepted
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nets-intranets.com
  namespace: gateway
  annotations:
    kubernetes.io/ingress.class: nginx  
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-apisix-gateway
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: id.nets-intranets.com
  namespace: identity
  annotations:
    kubernetes.io/ingress.class: nginx  
spec:
  rules:
    - host: id.nets-intranets.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80