apiVersion: v1
kind: Namespace
metadata:
  annotations:
    fluxcd.io/ignore: "false"
    linkerd.io/inject: enabled
  name: identity
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: identity
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: identity
      interval: 1m
  values:
    replicaCount: 1
