apiVersion: apps/v1
kind: Deployment
metadata:
  name: goweb
spec:
  selector:
    matchLabels:
      app: goweb
  replicas: 1
  template:
    metadata:
      labels:
        app: goweb
    spec: 
      containers:
      - name: koksmat-cli
        image: ghcr.io/koksmat-com/koksmat:v0.6.4
        ports:
          - containerPort: 5001
        command: ["koksmat"]
        args: ["serve"]               
        env:
        - name: DEBUG
          value: magicbox*
        - name: DATAOUT
          value: /exchange
        - name: DATABASE
          value: m365x65867376
        - name: DATABASEADMIN
          value: databaseAdmin
        - name: DATABASEPASSWORD
          value: tcmsJ4hGXqjiPeNwfbH
        - name: DATABASEURL
          value:  mongodb://prod-mongos.percona:27017
        - name: MAGICBOXURL
          value: http://web:5301/api/v1/exchange/sharedmailbox
---
apiVersion: v1
kind: Service
metadata:
  name: goweb
  labels:
    app: goweb
    service: goweb
spec:
  ports:
  - name: http
    port: 5001
    targetPort: 5001
  selector:
    app: goweb
