apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
spec:
  selector:
    matchLabels:
      app: docs
  replicas: 1
  template:
    metadata:
      labels:
        app: docs
    spec: 
      containers:
      - name: docs
        image: ghcr.io/koksmat-com/docs:v0.0.1
        ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: docs
  labels:
    app: docs
    service: docs
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: docs
