apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongogui
spec:
  selector:
    matchLabels:
      app: mongogui
  replicas: 1
  template:
    metadata:
      labels:
        app: mongogui
    spec: 
      containers:
      - name: mongogui
        image: ugleiton/mongo-gui:latest
        ports:
          - containerPort: 4321
        env:
        - name: MONGO_URL
          value: mongodb://databaseAdmin:tcmsJ4hGXqjiPeNwfbH@prod-mongos.percona:27017/?directConnection=true&authMechanism=DEFAULT&tls=false

---
apiVersion: v1
kind: Service
metadata:
  name: mongogui
  labels:
    app: mongogui
    service: mongogui
spec:
  ports:
  - name: http
    port: 4321
    targetPort: 4321
  selector:
    app: mongogui
