apiVersion: batch/v1
kind: CronJob
metadata:
  name: importrooms
spec:
  schedule: "10 * * * *"
  jobTemplate:
    spec:
      parallelism: 1
      completions: 1
      activeDeadlineSeconds: 600
      backoffLimit: 3

      template:
        metadata:
          labels:
            app: pwsh2
        spec: 
          restartPolicy: Never
          volumes:
          - name: shared-data
            emptyDir: {}          
          containers:
          - name: pwsh
            image: ghcr.io/koksmat-com/pwsh:v0.2.0
            command: ["pwsh"]
            args: ["-file", "./downloadRecipients.ps1"]               
            volumeMounts:
            - name: shared-data
              mountPath: /exchange            
            env:
            - name: DEBUG
              value: magicbox*
            - name: DATAOUT
              value: /exchange
            - name: EXCHAPPID
              valueFrom:
                secretKeyRef:
                  name: exchange
                  key: EXCHAPPID
            - name: EXCHORGANIZATION  
              valueFrom:
                secretKeyRef:
                  name: exchange
                  key: EXCHORGANIZATION   
            - name: EXCHCERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: exchange
                  key: EXCHCERTIFICATE   
                          
          - name: koksmat-cli
            image: ghcr.io/koksmat-com/koksmat:v0.2.0
            command: ["koksmat"]
            args: ["-i", "recipents.json","-d","exchange","-s","recipients"]               
            volumeMounts:
            - name: shared-data
              mountPath: /exchange            
            env:
            - name: DEBUG
              value: magicbox*
            - name: DATAOUT
              value: /exchange
            - name: MONGO_SERVER
              value:  mongodb://databaseAdmin:databaseAdmin123456@prod-mongos.percona:27017/?directConnection=true&authMechanism=DEFAULT
  