apiVersion: v1
kind: Namespace
metadata:
  annotations:
    fluxcd.io/ignore: "false"
    linkerd.io/inject: enabled
  name: monitor
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: monitor
spec:
  interval: 5m0s
  url: oci://registry-1.docker.io/bitnamicharts
  type: "oci"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitor
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: monitor
      interval: 1m
  values:
    replicaCount: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator 
  namespace: monitor
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana-operator 
      sourceRef:
        kind: HelmRepository
        name: bitnami 
        namespace: monitor
      interval: 1m
  values:
    replicaCount: 1