apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: magicbox
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nielsgregers/magicbox-web:v4
        env:
        - name: AMQP_URL
          value: amqp://worker:worker@magicbox-rabbitmq
        - name: MONGO_SERVER
          value: mongodb://root:eUPWmCoW6D@localhost:27017/?directConnection=true&authMechanism=DEFAULT
        ports:
          - containerPort: 3000

