apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec: 
      containers:
      - name: web
        image: ghcr.io/koksmat-com/ui:v0.0.1
        ports:
          - containerPort: 3001
        env:
        - name: DEBUG
          value: magicbox*
        - name: NEXTAUTH_SECRET
          value: 1fdas325esdv
        - name: KOKSMAT_HOST
          value: "https://magicbox.nexi-intra.com"
        - name: KOKSMAT_APPKEY
          value: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHAiOiJuaWVscyIsImtleSI6Ilx1MDAyNjFEQ1BhIU92ZkVxNGtOYCRIOU13WnJlbzU2eVlsUi1eXHUwMDNjaXNMZG5UYzJiVldRcGdYNzBCdEt7M3hTSXpcInxHOCIsIm5iZiI6MjM0fQ.Soo-yOAV-Zl-wR_BheO4qS29W9xqcpEr3BWy5hZJCA8"

---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
    service: web
spec:
  ports:
  - name: http
    port: 5301
    targetPort: 3001
  selector:
    app: web
