apiVersion: apps/v1
kind: Deployment
metadata:
  name: goweb
spec:
  selector:
    matchLabels:
      app: goweb
  replicas: 1
  template:
    metadata:
      labels:
        app: goweb
    spec: 
      containers:
      - name: koksmat-cli
        image: ghcr.io/koksmat-com/koksmat:v1.0.17
        ports:
          - containerPort: 5001
        command: ["koksmat"]
        args: ["serve"]               
        env:
        - name: DEBUG
          value: magicbox*
        - name: DATAOUT
          value: /exchange
        - name: DATABASE
          value: christianiabpos
        - name: DATABASEADMIN
          value: databaseAdmin
        - name: DATABASEPASSWORD
          value: tcmsJ4hGXqjiPeNwfbH
        - name: DATABASEURL
          value:  mongodb://prod-mongos.percona:27017
        - name: MAGICBOXURL
          value: http://web:5301/api/v1/exchange/sharedmailbox
        - name: EXCHAPPID
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHAPPID
        - name: EXCHORGANIZATION  
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHORGANIZATION   
        - name: EXCHCERTIFICATE
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHCERTIFICATE  
        - name: EXCHCERTIFICATEPASSWORD
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHCERTIFICATEPASSWORD                
      - name: koksmat-sharepoint
        image: ghcr.io/koksmat-com/koksmat:v1.0.17
        ports:
          - containerPort: 4321
        command: ["koksmat"]
        args: ["serve","core"]               
        env:
        - name: DEBUG
          value: magicbox*
        - name: DATAOUT
          value: /exchange
        - name: DATABASE
          value: christianiabpos
        - name: DATABASEADMIN
          value: databaseAdmin
        - name: DATABASEPASSWORD
          value: tcmsJ4hGXqjiPeNwfbH
        - name: DATABASEURL
          value:  mongodb://prod-mongos.percona:27017
        - name: MAGICBOXURL
          value: http://web:5301/api/v1/exchange/sharedmailbox
        - name: EXCHAPPID
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHAPPID
        - name: EXCHORGANIZATION  
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHORGANIZATION   
        - name: EXCHCERTIFICATE
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHCERTIFICATE  
        - name: EXCHCERTIFICATEPASSWORD
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHCERTIFICATEPASSWORD                
      - name: koksmat-admin
        image: ghcr.io/koksmat-com/koksmat:v1.0.17
        ports:
          - containerPort: 4322
        command: ["koksmat"]
        args: ["serve","admin"]               
        env:
        - name: DEBUG
          value: magicbox*
        - name: DATAOUT
          value: /exchange
        - name: DATABASE
          value: christianiabpos
        - name: DATABASEADMIN
          value: databaseAdmin
        - name: DATABASEPASSWORD
          value: tcmsJ4hGXqjiPeNwfbH
        - name: DATABASEURL
          value:  mongodb://prod-mongos.percona:27017
        - name: MAGICBOXURL
          value: http://web:5301/api/v1/exchange/sharedmailbox
        - name: EXCHAPPID
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHAPPID
        - name: EXCHORGANIZATION  
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHORGANIZATION   
        - name: EXCHCERTIFICATE
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHCERTIFICATE  
        - name: EXCHCERTIFICATEPASSWORD
          valueFrom:
            secretKeyRef:
              name: exchange
              key: EXCHCERTIFICATEPASSWORD                

---
apiVersion: v1
kind: Service
metadata:
  name: goweb
  labels:
    app: goweb
    service: goweb
spec:
  ports:
  - name: http
    port: 5001
    targetPort: 5001
  selector:
    app: goweb
---
apiVersion: v1
kind: Service
metadata:
  name: koksmat-sharepoint
  labels:
    app: goweb
    service: goweb
spec:
  ports:
  - name: http
    port: 4321
    targetPort: 4321
  selector:
    app: goweb
---
apiVersion: v1
kind: Service
metadata:
  name: koksmat-admin
  labels:
    app: goweb
    service: goweb
spec:
  ports:
  - name: http
    port: 4322
    targetPort: 4322
  selector:
    app: goweb
