apiVersion: v1
kind: Namespace
metadata:
  annotations:
    fluxcd.io/ignore: "false"
    linkerd.io/inject: enabled
  name: gateway
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: apiseven
  namespace: gateway
spec:
  interval: 5m0s
  url: https://charts.apiseven.com
  
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway
  namespace: gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: apisix
      sourceRef:
        kind: HelmRepository
        name: apiseven
        namespace: gateway
      interval: 1m
  values:
    replicaCount: 2
# ¨   extraVolumeMounts:
#     - name: gateway-debug
#       mountPath: /usr/local/apisix/conf/debug.yaml
#       readOnly: false
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dashboard
  namespace: gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: apisix-dashboard
      sourceRef:
        kind: HelmRepository
        name: apiseven 
        namespace: gateway
      interval: 1m
  values:
    replicaCount: 2
    config:
      conf:
        etcd:
          endpoints:
          - gateway-etcd:2379
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress
  namespace: gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: apisix-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: apiseven 
        namespace: gateway
      interval: 1m
  values:
    replicaCount: 1
    config:
      apisix:
        adminAPIVersion: v2    
        serviceName: gateway-apisix-admin
        serviceNamespace: gateway


