---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description:  This is the ingress controller for the cluster
  name: nginx
  namespace: ingress
spec:
  interval: 1h0m0s
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/nginx-ingress-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description:  This is the ingress controller for the cluster
  name: nginx
  namespace: ingress
spec:
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: nginx
  interval: 1h0m0s
  values:
    controller:
      config:
        use-forwarded-headers: "true"
    defaultBackend:
      enabled: "true"
    image:
      pullPolicy: Always
      repository: docker.io/bitnami/nginx-ingress-controller
      tag: 1.0.0
    metrics:
      enabled: "true"
    rbac:
      create: "true"
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      type: LoadBalancer

